# Primal Form

P2

In [102]:
import numpy as np
import pandas as pd
import cvxpy as cvx
import warnings
warnings.filterwarnings("ignore")

In [103]:
pd.read_csv('train.csv', header=None)

0     1     2     3     4     5     6     7     8     9    ...   191  \
0     0.0 -0.36 -0.91 -0.99 -0.57 -1.38 -1.54 -1.64  1.29  0.65  ...  1.15   
1     1.0 -1.40 -1.90  0.09  0.29 -0.30 -1.30  1.13 -2.38 -1.16  ...  0.48   
2     1.0 -0.43  1.45 -0.68 -1.58  0.32 -0.14  0.23 -1.01 -0.39  ... -0.94   
3     1.0 -0.76  0.30 -0.57 -0.33 -1.50  1.84  1.37  0.23  0.66  ... -0.42   
4     0.0 -0.76  1.36  0.00 -1.44 -1.27 -0.76 -1.42 -0.58  0.11  ... -0.44   
5     1.0 -0.70  0.83 -1.57  1.15  0.79 -0.02 -0.24 -2.58  0.73  ... -0.37   
6     1.0 -0.33 -1.78 -1.30  0.00  0.43  0.90  1.01 -0.76 -1.70  ... -0.38   
7     0.0 -0.59  0.25  0.29  2.21  0.05 -1.45  0.55 -0.40 -0.39  ... -1.77   
8     0.0 -2.57  1.27 -1.54 -0.46 -0.13 -0.45 -0.70  1.24  0.84  ... -0.54   
9     0.0 -0.99 -1.19  1.73  1.20 -0.42 -0.44 -0.40 -0.88 -1.48  ...  0.76   
10    0.0  1.03  1.38  1.00 -1.73  1.61 -1.40 -0.43 -0.87  3.30  ... -1.14   
11    1.0 -0.51 -1.29 -0.96 -0.56 -0.23 -0.80  1.60 -0.89 -0.07  ... -2.54   
12    1.0  0.81 -0.25  0.49 -0.16 -0.35  0.84  0.74  1.42 -0.68  ...  1.81   
13    0.0  0.88  0.71  0.30  1.72 -1.31  1.76  0.52  0.44  1.19  ... -0.55   
14    0.0  0.34  0.90  0.72  1.37 -0.66 -0.53  1.88  0.61  1.26  ...  2.65   
15    0.0  2.66 -0.43 -0.53  0.71 -0.10 -3.36  1.02  0.16  1.75  ... -1.27   
16    1.0  1.05 -1.79  0.90  0.68  0.54 -1.93 -0.71 -0.18  1.40  ...  1.18   
17    0.0  0.76  0.31  1.58  0.37 -0.70  0.83  0.75 -0.86  0.32  ...  0.12   
18    1.0 -0.25 -0.23  0.61  1.34  3.18 -0.51 -0.22  1.47 -0.74  ... -0.18   
19    0.0  0.44 -0.65  2.28  1.74 -1.23 -0.79  0.55 -1.83  0.33  ... -0.22   
20    1.0  1.35 -1.47  1.60 -1.84 -0.05 -0.30  1.11  0.89 -0.09  ...  0.42   
21    0.0 -1.34  1.23  0.93  0.99  1.44 -0.89  0.30 -0.29  0.14  ...  0.25   
22    1.0 -0.16  0.21  0.16  0.84  0.29 -0.28 -0.22 -0.58 -1.52  ...  0.66   
23    0.0  0.18 -0.92  1.47  1.41 -0.43 -0.86  0.43  0.27 -1.15  ... -0.43   
24    0.0 -0.70  1.11 -0.65  0.44 -0.57  0.45  1.69 -0.18  0.05  ... -0.96   
25    1.0  0.91  1.94  0.59 -1.32 -0.19  0.87 -0.43  0.75 -0.25  ...  0.59   
26    1.0 -1.06  0.46  0.32 -0.37 -1.03  0.18  0.64 -0.09  1.07  ...  0.90   
27    1.0  1.37 -0.32  0.27 -0.97  0.71 -0.88 -0.55 -0.78  0.52  ...  0.70   
28    0.0  1.01 -1.13  1.49  0.27 -1.03  0.84  0.37 -0.64 -0.15  ...  0.90   
29    1.0  0.41 -0.19  0.88  0.07  0.99  1.11 -0.16  0.27 -1.46  ...  2.22   
...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
8470  0.0 -0.37  0.78  1.14  0.45 -2.21 -1.07 -1.01 -0.38 -0.53  ...  1.16   
8471  0.0  0.16  0.84 -1.09 -0.71  0.03 -1.20  0.72 -0.17 -0.17  ...  0.84   
8472  0.0 -1.47  0.62 -1.56 -0.51 -1.15  0.63 -0.38 -0.87  0.02  ... -0.41   
8473  0.0  0.60 -0.56 -0.04 -0.14  1.61  2.37  1.08 -1.24  0.61  ...  0.29   
8474  1.0 -0.43 -2.00  0.03 -0.35  0.47  0.19 -0.01  1.16 -1.24  ...  0.04   
8475  1.0 -1.02 -1.72  1.84  0.09 -0.73  0.67  0.08 -0.26  2.43  ...  1.29   
8476  1.0  1.49  0.14  0.09  1.24  0.87  0.39  1.21 -0.17  0.30  ... -1.50   
8477  1.0 -0.16 -0.04 -1.08 -0.00 -0.37  0.00  0.58  1.09  0.41  ...  0.70   
8478  1.0 -1.68  1.69 -0.74  0.08 -0.13 -1.00 -1.00  0.21  2.19  ...  0.64   
8479  1.0 -0.66 -0.40  1.45  0.95 -0.49 -0.61  0.23  0.13  1.25  ... -1.03   
8480  0.0  0.12 -0.16  0.53 -1.13 -0.53  0.28  0.41 -0.52 -1.43  ...  1.55   
8481  1.0  0.93  0.83  0.74  1.46  0.61  1.45 -1.08  1.97 -1.82  ...  0.20   
8482  0.0 -1.22  0.80  1.12 -1.95 -2.48  0.67  0.40 -0.24 -0.73  ... -1.03   
8483  0.0 -0.66 -0.15  0.96 -0.27  0.23 -0.75 -0.02  0.26  1.28  ... -0.64   
8484  0.0  2.22  1.48 -0.38 -1.56  0.41 -0.67  0.03 -1.27 -0.94  ...  0.68   
8485  1.0 -0.33  0.69  0.60 -0.07  0.27  1.85  0.76 -0.84  1.59  ... -0.78   
8486  1.0 -0.31  1.17  0.14  1.31 -1.13  0.73 -2.44  3.29  1.12  ...  1.14   
8487  1.0  1.46 -0.19 -1.24  0.27  0.40 -0.94  0.25  0.91 -0.59  ... -1.15   
8488  0.0 -0.58  0.55  0.34  0.72  2.08  1.27  1.37  2.69 -0.02  ... -0.15   
8489  0.0 -0.03  0.38  0.34 

In [79]:
LL = 4000

In [104]:
def loadData(filename):
    data=pd.read_csv(filename, header=None)
    x=np.array(data.iloc[:,1:])
    y=np.array(data.iloc[:,0])
    for i in range(len(y)):
        if y[i]==0:
            y[i]=-1
    y=y.reshape(len(y),1)
    return x,y

In [105]:
data_train,label_train=loadData('train.csv')
data_test,label_test=loadData('test.csv')
regularisation_para_C=100

In [106]:
def svm_train_primal ( data_train , label_train , regularisation_para_C ):
    N,M=data_train.shape
    var_w=cvx.Variable((M,1))
    var_b=cvx.Variable()
    var_k=cvx.Variable((N,1))
    obj=cvx.Minimize(0.5*cvx.norm2(var_w)**2+regularisation_para_C/N*cvx.sum(var_k))
    cons=[
        cvx.multiply(label_train,data_train*var_w+var_b)>=1-var_k,
        var_k>=0
    ]
    prob=cvx.Problem(obj,cons)
    prob.solve()
    svm_model={
        'w':var_w.value,
        'b':var_b.value
    }
    return svm_model

In [107]:
def svm_predict_primal ( data_test , label_test , svm_model ):
    w=svm_model['w']
    b=svm_model['b']
    label_pred=np.dot(data_test,w)+b
    pred_true=0
    pred_total=len(label_test)
    for i in range(pred_total):
        if label_pred[i][0]*label_test[i][0]>0:
            pred_true+=1
    return pred_true/pred_total

In [108]:
svm_model = svm_train_primal ( data_train[:LL] , label_train[:LL] , regularisation_para_C )
test_accuracy = svm_predict_primal ( data_test , label_test , svm_model )

In [110]:
sum_w=np.sum(svm_model['w'])
print('the solution of b:{:.5f}'.format(svm_model['b']))
print('sum of all dimensions of w solution:{:.5f}'.format(sum_w))
print('test accuracy of svm_model:{:.5f}'.format(test_accuracy))

the solution of b:1.77981
sum of all dimensions of w solution:-0.14522
test accuracy of svm_model:0.96800


P5

In [86]:
def getSupports_primal(data_train,svm_model):
    w=svm_model['w']
    b=svm_model['b']
    d=np.dot(data_train,w)+b
    positive=min(d[d>0])
    negative=max(d[d<0])
    index_positive=np.argwhere(d==positive)
    index_negative=np.argwhere(d==negative)
    print(data_train[index_positive])
    print(data_train[index_negative])

In [87]:
getSupports_primal(data_train,svm_model)

[[[-1.47  1.27  0.87  0.08 -1.45 -1.65 -0.76  1.75  2.22  0.01 -1.36
    0.31  0.83 -1.55  1.45 -0.16 -1.38 -1.4   2.15 -0.98 -0.39  1.19
   -2.11  0.75  0.59 -1.05  0.32  0.37 -2.15 -0.81  0.73  0.37 -1.11
   -1.43 -1.86 -2.2  -1.95 -1.69 -1.2  -1.51 -0.5   0.04 -0.96 -1.02
   -2.73 -1.72 -0.68 -0.24 -0.67  1.13  0.75  0.13 -0.05  0.86 -0.18
   -0.42  0.56  0.07 -0.99 -0.54 -0.54  3.11 -1.09 -2.66  0.57 -1.01
   -0.93  0.36 -0.87  0.26 -0.39 -0.13  0.4   1.6   0.12  2.91  1.48
   -0.59  1.77  0.49  0.47  0.36 -0.76 -1.13 -0.6  -0.18 -0.66  0.84
   -1.5   3.65  0.27 -0.72 -0.78  1.78  1.29  1.42 -0.6   1.94 -1.31
   -1.83 -0.49  1.9  -0.37  2.15 -1.07  0.43  0.49 -0.2   0.28  0.31
    1.64  0.68 -0.83  0.21 -1.19  0.09 -1.6  -0.47 -2.4   0.44  0.99
    1.02 -0.87  0.25 -0.46 -0.02  1.29 -0.51 -2.55 -0.15 -2.14 -1.
    0.48 -0.75 -2.5   1.01 -1.37  1.06 -0.72 -2.25 -0.01 -1.94 -2.38
    1.35 -1.49  0.51  0.5  -0.08 -1.35  0.43 -0.18  0.58  1.34  0.79
    0.84  4.89  0.59 -0.26 -0.16 -0.

P7

In [123]:
def chooseC():
    optimal_acc=-1
    optimal_C=-1
    for i in range(-10,11):
        C=2**i
        str_C='2^'+str(i)
        svm_model = svm_train_primal ( data_train , label_train , C)
        test_accuracy = svm_predict_primal ( data_test , label_test , svm_model )
        print('C:{}--accuracy:{}'.format(str_C,test_accuracy))
        if test_accuracy>optimal_acc:
            optimal_C='2^'+str(i)
            optimal_acc=test_accuracy
    return optimal_C

In [124]:
optimal_C=chooseC()
print('the optimal C is ',optimal_C)

C:2^-10--accuracy:0.9053333333333333
C:2^-9--accuracy:0.906
C:2^-8--accuracy:0.9046666666666666
C:2^-7--accuracy:0.9066666666666666
C:2^-6--accuracy:0.904
C:2^-5--accuracy:0.912
C:2^-4--accuracy:0.934
C:2^-3--accuracy:0.9513333333333334
C:2^-2--accuracy:0.9633333333333334
C:2^-1--accuracy:0.9693333333333334
C:2^0--accuracy:0.97
C:2^1--accuracy:0.9726666666666667
C:2^2--accuracy:0.9733333333333334
C:2^3--accuracy:0.9733333333333334
C:2^4--accuracy:0.974
C:2^5--accuracy:0.972
C:2^6--accuracy:0.9726666666666667
C:2^7--accuracy:0.9706666666666667
C:2^8--accuracy:0.9693333333333334
C:2^9--accuracy:0.968
C:2^10--accuracy:0.9693333333333334
the optimal C is  2^4


P8

In [122]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svm = SVC(kernel='linear')
svm.fit(data_train,label_train)
label_pred=svm.predict(data_test)
print('test accuracy of sklean SVC:{:.5f}'.format(accuracy_score(label_test,label_pred)))

test accuracy of sklean SVC:0.96800


# Dual Form

p3

In [112]:
import cvxpy as cp
import numpy as np

def svm_train_dual ( data_train , label_train , regularisation_para_C ):
    N,M=data_train.shape
    
    # y.T: 1xN NxM => 1xM    @ Mx1
    # (y.T@X) @ (y.T@X).T
    # = (y.T@X) @ (X.T @ y)
    # = y.T @ (X@X.T) @ y
    # (AB)^T = B^T A^T
    # A@B@C = A@(B@C) 
    X, y = data_train, label_train
    
    A=np.multiply(np.dot(label_train,label_train.T),np.dot(data_train,data_train.T))
    #A=label_train.T @ data_train @ data_train.T @ label_train
    alpha=cp.Variable((N,1))
    v = np.multiply(y, X)
    print(v.T.shape)
#     obj=cp.Maximize(cp.sum(alpha)-0.5*cp.quad_form(alpha,A))
    obj=cp.Maximize(cp.sum(alpha)- 0.5 * cp.sum_squares(v.T @ alpha))
    constraints=[
        alpha <= regularisation_para_C / N,
        alpha>=0,
        cp.sum(cp.multiply(alpha,label_train))==0
    ]
    prob=cp.Problem(obj, constraints)
    prob.solve()
    svm_model={
        'alpha':alpha.value
    }
    return svm_model

In [113]:
svm_model = svm_train_dual ( data_train[:LL] , label_train[:LL] , regularisation_para_C )

(200, 4000)


In [115]:
sum_a=np.sum(svm_model['alpha'])
print(sum_a)

7.291258324598102


In [91]:
print('sum of all dimensions of alpha solution:{:.5f}'.format(sum_a))

sum of all dimensions of alpha solution:7.29126


p4

In [92]:
def getParams(svm_model, data_train, label_train):
    N=len(label_train)  # dataset size
    alpha=svm_model['alpha']  # N
    # X data_train: NxM  # M -> feature size
    # y label_train: N
    # w=np.sum(np.dot(np.dot(data_train, alpha),label_train))
    # print(data_train.shape, label_train.shape, alpha.shape)
    # (100, 200)              (100, 1)           (100, 1)
    #    100, 200      100, 1
    # print((alpha * label_train).shape)
    w = data_train.T @ (alpha * label_train)
    # w -> Nx1
    
    index=[]
    M, _ = alpha.shape
    for i in range(M):
        if alpha[i]>0:
            index.append(i)
    b=0
    x = data_train
    for i in index:
        b+=label_train[i]
        for j in range(N):
            b-=alpha[i]*label_train[i]*np.dot(x[i],x[j])
    b/=N
    return w,b

In [93]:
getParams(svm_model, data_train[:LL], label_train[:LL])

(array([[-2.55939591e-02],
        [-1.14007921e-01],
        [ 4.32855212e-02],
        [-5.18819300e-02],
        [ 7.53472963e-02],
        [-7.84397544e-03],
        [ 2.65824264e-02],
        [-9.45503426e-03],
        [ 4.40336593e-03],
        [ 1.58195680e-03],
        [ 9.38970723e-02],
        [ 6.42173161e-02],
        [ 6.94519223e-02],
        [ 6.27878091e-02],
        [ 1.89513082e-02],
        [-2.33295766e-02],
        [-5.83849380e-02],
        [-4.54946031e-02],
        [-5.19864228e-02],
        [-2.69134823e-02],
        [-1.74617965e-03],
        [ 4.38137199e-02],
        [-8.54178243e-03],
        [-4.56328690e-02],
        [-1.88722859e-02],
        [-1.86577877e-02],
        [-4.35992174e-03],
        [ 1.05853557e-02],
        [-7.25165256e-02],
        [ 1.13775842e-01],
        [-2.23632064e-02],
        [-1.37427911e-02],
        [ 5.99524516e-02],
        [-2.08665832e-02],
        [ 8.54609108e-02],
        [-3.98405560e-02],
        [ 2.32234759e-02],
 

p6

In [119]:
def getSupports_dual(data_train,svm_model):
    alpha=svm_model['alpha']
    supports=np.array([])
    for i in range(len(alpha)):
        if alpha[i]>0:
            supports=np.append(supports, list(data_train[i]))
    return np.array(supports)

In [120]:
svm_model

{'alpha': array([[ 2.49983249e-02],
        [-2.02102464e-06],
        [-3.25359846e-07],
        ...,
        [-3.05192800e-06],
        [-3.80953984e-06],
        [-1.60635358e-07]])}

In [121]:
getSupports_dual(data_train,svm_model)

array([-0.36, -0.91, -0.99, ...,  0.25, -1.17, -0.64])

In [100]:
getParams(svm_model, data_train[:LL], label_train[:LL])[-1]

array([1.79757824])

In [49]:
a * b

array([[11],
       [24],
       [39]])

In [50]:
np.multiply(a, b)

array([[11],
       [24],
       [39]])

In [52]:
a.T, b

(array([[1, 2, 3]]),
 array([[11],
        [12],
        [13]]))

In [54]:
a.T @ b

array([[74]])